[project]
name = "ngstents"
dynamic = ["version"]
authors = [{name="Jay Gopalakrishnan", email= "gjay@pdx.edu"}]
description = "Spacetime tent facilities for solving hyperbolic equations"
urls = {github="https://github.com/jayggg/ngstents"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "ngsolve==6.2.2607",
  "matplotlib",
]
classifiers = [
  "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)"
]

[build-system]
requires = [
  "ngsolve==6.2.2607",
  "setuptools>=45",
  "setuptools_scm>=8",
  "toml; python_version >= '3.11'",
  "tomli>=1.1.0; python_version < '3.11'",
  "scikit-build-core>=0.9.0",
]
build-backend = "scikit_build_core.build"

##########################################################################
# Settings for cibuildwheel to build .whl files for Windows/Mac/Linxu
# DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU ARE DOING
##########################################################################

[tool.scikit-build]
minimum-version = "0.9"
cmake.source-dir = "src" # set this if the root CMakeLists.txt is in a subdirectory
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]
local_scheme = "no-local-version"

[tool.cibuildwheel]
manylinux-x86_64-image = "cerbsim/manylinux_2_28_x86_64_cuda_12.9"
skip = """
  *_i686
  *musllinux*
  *win32
"""

[tool.cibuildwheel.linux]
repair-wheel-command = "mv {wheel} {dest_dir} && rename linux_x86_64 manylinux_2_28_x86_64.manylinux2014_x86_64 {dest_dir}/*-linux_x86_64*.whl"

[tool.cibuildwheel.macos]
environment = {MACOSX_DEPLOYMENT_TARGET="10.15"}
repair-wheel-command = ""
archs = ["universal2"]
